/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 28/03/2022 09:55:51
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            24000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     280000000
#define MX_HCLKFreq_Value                       140000000
#define MX_CortexFreq_Value                     280000000
#define MX_APB1Freq_Value                       70000000
#define MX_APB2Freq_Value                       70000000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32768
#define MX_USBFreq_Value                        186666666
#define MX_WatchDogFreq_Value                   32000
#define MX_SPDIFRXFreq_Value                    186666666
#define MX_MCO1PinFreq_Value                    24000000
#define MX_MCO2PinFreq_Value                    280000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DEBUG      --------------------------------*/

#define MX_DEBUG                                1

/* GPIO Configuration */

/* Pin PA15 */
#define MX_DEBUG_JTDI_Pin                       PA15
#define MX_JTDI                                 DEBUG_JTDI

/* Pin PA14 */
#define MX_DEBUG_JTCK_SWCLK_Pin                 PA14
#define MX_JTCK                                 DEBUG_JTCK_SWCLK

/* Pin PB4 */
#define MX_DEBUG_JTRST_Pin                      PB4

/* Pin PB3 */
#define MX_DEBUG_JTDO_SWO_Pin                   PB3
#define MX_JTDO_TRACESWO                        DEBUG_JTDO_SWO

/* Pin PA13 */
#define MX_DEBUG_JTMS_SWDIO_Pin                 PA13
#define MX_JTMS                                 DEBUG_JTMS_SWDIO

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB6 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_GPIO_FM6                   __NULL
#define MX_USART1_TX_Pin                        PB6
#define MX_USART1_TX_GPIOx                      GPIOB
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PB7 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PB7
#define MX_USART1_RX_GPIOx                      GPIOB
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_RX_GPIO_FM7                   __NULL

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_WAKEUP                               PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PG11 */
#define MX_PG11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG11_Pin                             PG11
#define MX_PG11_GPIOx                           GPIOG
#define MX_PG11_PinState                        GPIO_PIN_RESET
#define MX_PG11_GPIO_PuPd                       GPIO_NOPULL
#define MX_USER_LED1                            PG11
#define MX_PG11_GPIO_Pin                        GPIO_PIN_11
#define MX_PG11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG2 */
#define MX_PG2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG2_Pin                              PG2
#define MX_PG2_GPIOx                            GPIOG
#define MX_PG2_PinState                         GPIO_PIN_RESET
#define MX_PG2_GPIO_PuPd                        GPIO_NOPULL
#define MX_USER_LED2                            PG2
#define MX_PG2_GPIO_Pin                         GPIO_PIN_2
#define MX_PG2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

